# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# Available pre-commit hooks
#   https://pre-commit.com/hooks.html

default_language_version:
    python: python3.7
fail_fast: true
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    -   id: check-added-large-files
    -   id: check-json
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: check-symlinks
    -   id: check-vcs-permalinks
    -   id: requirements-txt-fixer
    -   id: forbid-new-submodules
    -   id: pretty-format-json
        args: [
          '--autofix',
          '--indent', '4',
          '--no-sort-keys',
        ]
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
- repo: https://github.com/jumanjihouse/pre-commit-hooks
  sha: 1.11.2
  hooks:
    - id: forbid-binary
    - id: git-dirty  # Configure in .gitignore
    - id: markdownlint # Configure in .mdlrc
    - id: script-must-have-extension
    - id: script-must-not-have-extension
    - id: shellcheck
-   repo: meta
    hooks:
    -   id: check-useless-excludes
-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.7
    hooks:
    -   id: insert-license
        files: \.cc
        args:
        - --license-filepath
        - etc/license-header
        - --comment-style
        - //
    -   id: insert-license
        files: \.h
        args:
        - --license-filepath
        - etc/license-header
        - --comment-style
        - //
    -   id: insert-license
        files: \.proto
        args:
        - --license-filepath
        - etc/license-header
        - --comment-style
        - //
    -   id: insert-license
        files: \.py
        args:
        - --license-filepath
        - etc/license-header
    -   id: insert-license
        files: \.bazelignore
        args:
        - --license-filepath
        - etc/license-header
    -   id: insert-license
        files: \.bazelrc
        args:
        - --license-filepath
        - etc/license-header
-   repo: https://github.com/Yelp/detect-secrets
    rev: v0.13.0
    hooks:
    -   id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.740
    hooks:
    -   id: mypy
        args: [--no-strict-optional, --ignore-missing-imports]
-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    -   id: black
        language_version: python3.7
# -   repo: https://github.com/pocc/pre-commit-hooks.git
#     rev: v0.2.0
#     hooks:
#     -   id: clang-format
#     -   id: clang-tidy
- repo: https://gitlab.com/daverona-env/pre-commit-cpp
  rev: 0.6.0          # use the most recent version
  hooks:
  - id: clang-format  # formatter of C/C++ code based on a style guide: LLVM, Google, Chromium, Mozilla, and WebKit available
  # - id: cpplint       # linter (or style-error checker) for Google C++ Style Guide
  - id: cppcheck      # static analyzer of C/C++ code
